# Generated by Django 2.2 on 2021-01-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
